### ISSUE TITLE
Potential scoping issue?

### ISSUE THREAD

**Issue by toddlang** [csnewman/BlazorSignalR#11]
I'm not sure if this is actually an issue...but given that the IJSRuntime is a Scoped object, is it not a concern that BlazorHttpContectionFactory is caching it and handing it to new connections?  Perhaps I haven't had enough coffee...this just feels...strange.

**Comment by CatoLeanTruetschel** [comment]
The js runtime is registered as singleton in blazor. Razor components (server-side) is not working yet anyway. I have a prototype for it where I resolved this, but there are some minor issues that need to be fixed.  

Even if it were scoped, I don't see a problem, as each user runs in its own scope (in Razor Components f.e.) and you want a separate SignalR connection per user anyway.

**Comment by toddlang** [comment]
I'm pretty sure it's scoped:
https://github.com/aspnet/AspNetCore/blob/33839dc66a9e6eb730e22e7b6d9d381bcf7b4779/src/Components/Server/src/DependencyInjection/ComponentServiceCollectionExtensions.cs#L46

Of course, here it's singleton:
https://github.com/aspnet/AspNetCore/blob/7daa0e01459539da15b653c4740b5e0f9834c59b/src/Components/Blazor/Blazor/src/Hosting/WebAssemblyHostBuilder.cs#L90

I guess I'm just having a lot of problems mentally juggling scoping on things.  I wanted to have a "singleton" ISignalService that I utilize across my pages, and having internals be Scoped means that I'm registering things incorrectly.  Oi.

**Comment by CatoLeanTruetschel** [comment]
You are right, it is scoped but this is NOT the your ordinary service collection, it is the service collection the HubConnectionBuilder uses internally. There is a separate HubConnectionBuilder for each SignalR connection you open.

If you want to register the HubConnection into your own service collection, this does not interfere with what is done internally.

**Comment by CatoLeanTruetschel** [comment]
I'm doing this in my own project aswell and it works as it should. See: https://github.com/AI4E/AI4E/blob/samples/src/AI4E.Routing.SignalR.Client/ServiceCollectionExtension.cs#L30

**Comment by toddlang** [comment]
Alrighty, thanks for taking the time to address a neurotic post.  :)
