### ISSUE TITLE
Update to .net 3.0 preview 4

### ISSUE THREAD

**Issue by stavroskasidis** [csnewman/BlazorSignalR#17]
Currently the latest version is not compatible with .net core 3.0 preview 3. Any plans to update to preview 4 ?

**Comment by CatoLeanTruetschel** [comment]
@stavroskasidis The current version is compatible with preview3.  

There is no support for preview 4, as there are some changes in the naming of the blazor projects (Razor components was named back to server-side blazor). The `Microsoft.AspNetCore.Components.*` packages that we are dependent on have to be replaced with their `Microsoft.AspNetCore.Blazor.*` counterparts.   

I will file a PR for this today.

**Comment by stavroskasidis** [comment]
Thank you

**Comment by csnewman** [comment]
@stavroskasidis  ```0.6.0-blazor-3.0.0-preview4-19216-03``` has been released.
