### ISSUE TITLE
Disconnect after a few seconds in Blazor 0.7.0

### ISSUE THREAD

**Issue by stavroskasidis** [csnewman/BlazorSignalR#2]
After I start a connection, a few seconds later the ` OnDisconnected` method triggers on the hub. This does not occur with Blazor 0.6.0.

**Comment by csnewman** [comment]
Have you checked the console log inside of chrome? Or the network view?

**Comment by csnewman** [comment]
You may need to enable logging from https://github.com/csnewman/BlazorSignalR/blob/eccf7eca82d29281590b263166cd09e195247a21/test/BlazorSignalR.Test.Client/Pages/ChatComponent.cs#L34L37 to see more information. Also try upgrading to the latest 0.3.0 version I have just uploaded.

**Comment by csnewman** [comment]
Reopen if you still experience issues.
