### ISSUE TITLE
Remove workaround for System.Memory in test project

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [csnewman/BlazorSignalR#21]
Can we remove the [workaround](https://github.com/csnewman/BlazorSignalR/blob/master/test/BlazorSignalR.Test.Client/BlazorSignalR.Test.Client.csproj#L21-L24) for the `System.Memory` assembly in the test project?  

I didn't test this during the upgrade to Asp.Net Core 3.0 preview 4.

**Comment by csnewman** [comment]
Do you know the status of this? Or is it a, "it works with out it"? Sort of deal?

It was added as a temporary solution, so I'm more than happy for it to be removed if the "test" project works without it.

**Comment by CatoLeanTruetschel** [comment]
I can test this tomorrow, but I cannot say of the cut whether it is still necessary.

**Comment by CatoLeanTruetschel** [comment]
The workaround is still necessary the test project throws if it is not present.   

![grafik](https://user-images.githubusercontent.com/12112026/57120854-4f904680-6d74-11e9-9c50-2303d5f82fd4.png)

I will open another issue in the mono repo for this as proposed in the Asp.Net Core Issue I files. We may leave this issue as tracking issue and not to forget to remove the workaround if this is fixed in mono.

**Comment by csnewman** [comment]
@AndreasTruetschel Did you create an issue? If so, please reference the issue.

**Comment by CatoLeanTruetschel** [comment]
Sure, https://github.com/mono/mono/issues/14326 is the issue in the mono repo.
