### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by liyanjie2048** [csnewman/BlazorSignalR#27]
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at WebSocket.s.onmessage (http://localhost:1234/_content/BlazorSignalR.JS:1:2814)

s.onmessage @ WebSocketsTransport.ts:33

**Comment by csnewman** [comment]
Ahh, Thats quite unfortunate!

I assume you are sending/receiving none asci text? Or are you trying to send/receive some binary data?

**Comment by liyanjie8712** [comment]
Object instance,maybe contains Unicode string properties

**Comment by liyanjie8712** [comment]
I updated to the latest version and the problem disappeared.
