### ISSUE TITLE
Migrating to Asp.Net Core 3 preview 5 throws NullReferenceException

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [csnewman/BlazorSignalR#28]
When using the project in an Asp.Net Core 3 Preview 5 Blazor App, a `System.NullReferenceException` is thrown client-side. This is true for the sample project too.  

In the sample, while the connection is done, trying to send a message results in this error printed to the console:  

![grafik](https://user-images.githubusercontent.com/12112026/58351216-6e13ca00-7e68-11e9-915b-543231f8c68c.png)

**Comment by CatoLeanTruetschel** [comment]
This is because the string variable in the `ChatComponent` is null, if the corresponding input is empty. Checking it for null and replacing it with an empty string fixes the problem. We should either do this to all `Invoke*` calls in the `ChatComponent` or file a bug in the Asp.Net Core repo.

**Comment by csnewman** [comment]
Is the issue that you can't invoke a method with null arguments?

**Comment by CatoLeanTruetschel** [comment]
Yes

**Comment by csnewman** [comment]
I feel like that is more of an Asp.net core issue then.

**Comment by csnewman** [comment]
Inactive
