### ISSUE TITLE
update for preview 9

### ISSUE THREAD

**Issue by dazinator** [csnewman/BlazorSignalR#37]
I'd like to update my blazor app to preview 9, but cannot until this dependency is also compiled for preview 9. I'll have a go at a PR.

**Comment by dazinator** [comment]
Oh wait - there are 2 PR's for this already! haha... In which case... I'll try to be more patient..

**Comment by csnewman** [comment]
`0.10.0-blazor-3.0.0-preview9.19424.4` has been released on NuGet.
