### ISSUE TITLE
.Net Core 3.0 Preview with Razor Components

### ISSUE THREAD

**Issue by sethi-ishmeet** [csnewman/BlazorSignalR#4]
Gives the following error:
```
Method 'get_MinorVersion' in type 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' from assembly 'Microsoft.AspNetCore.SignalR.Protocols.Json, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'
```
when initializing 
`HubConnectionBuilder factory = new HubConnectionBuilder();`

**Comment by csnewman** [comment]
Can you post the full stracktrace?

**Comment by sethi-ishmeet** [comment]
```
at Microsoft.Extensions.DependencyInjection.JsonProtocolDependencyInjectionExtensions.AddJsonProtocol[TBuilder](TBuilder builder, Action`1 configure)
   at Microsoft.Extensions.DependencyInjection.JsonProtocolDependencyInjectionExtensions.AddJsonProtocol[TBuilder](TBuilder builder)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder..ctor()
   at RazorComponentsTest.App.Services.SignalService..ctor() in C:\Users\sethi\Desktop\repos\RazorComponentsTest\RazorComponentsTest\RazorComponentsTest.App\Services\SignalService.cs:line 26
```

**Comment by csnewman** [comment]
Whats the contents of your csproj files?

From what I've seen, theres a new API breaking change in official signalr client, however this project should be unaffected. Are you using the latest signalr c# client versions? (I will be able to see this from your csproj file)

**Comment by sethi-ishmeet** [comment]
Here's a snippet from the csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorSignalR" Version="0.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview-19075-0444" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Build" Version="3.0.0-preview-19075-0444" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.1.0" />
  </ItemGroup>

</Project>
```

**Comment by csnewman** [comment]
The ```Microsoft.AspNetCore.SignalR``` package shouldn't be installed clientside

**Comment by sethi-ishmeet** [comment]
Still getting the same error after removing it.

**Comment by csnewman** [comment]
Could you create a small project which reproduces this issue?

**Comment by sethi-ishmeet** [comment]
yes give me a moment

**Comment by sethi-ishmeet** [comment]
Here you go: https://github.com/sethi-ishmeet/RazorComponentsTest

**Comment by csnewman** [comment]
The issue is caused by using an outdated signalr client.

You need to use the preview version to match:
```
<ItemGroup>
    <PackageReference Include="BlazorSignalR" Version="0.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview-19075-0444" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Build" Version="3.0.0-preview-19075-0444" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.0.0-preview-19075-0444" />
  </ItemGroup>
```


On a side note, you're trying to use this package with RazorComponents, which is server side blazor. Currently this package does not support this setup, It just needs a simple fix to be applied, however I do not see the purpose of using SignalR in this way.

You are routing your signalr requests from the web server, to the web browser, and then out to the target signalr server.  You should probably skip the web browser all together.

**Comment by sethi-ishmeet** [comment]
I see. So what’d you suggest should be done if I’d like to update my pages real time in razor components? Is there an example you could probably share?

**Comment by csnewman** [comment]
The entire purpose of razor components is to allow that functionality.

I'm not certain if there is an official recommended way to do this, but basically you just need to keep references to your components. Then when you update the page content and ask for it to be rerendered the client will display the changes. However you'll have to make sure you keep weak GC references to stop memory ballooning.

SignalR is already being used by razor components for this functionality. This is why it only makes sense to use this library with blazor, where there's no constant connection to the server.

**Comment by DNF-SaS** [comment]
You won't need any separate SignalR if you're using Razor components.
