### ISSUE TITLE
Issues with Blazor 0.8.0-preview-19104-04

### ISSUE THREAD

**Issue by netclectic** [csnewman/BlazorSignalR#5]
Trying to use the NuGet package with Blazor 0.8.0-preview-19104-04 results in build errors...

```Error	CS0433	The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'```

```Error	CS0433	The type 'BlazorWebAssemblyHost' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	```

**Comment by csnewman** [comment]
This is caused by the major refactor in Blazor 0.8 and the release of Razor Components. Should be a simple fix of just updating the type and package names, I will release a fix sometime this week.

**Comment by CatoLeanTruetschel** [comment]
@csnewman Just did that ^^ and opened a PR for it.

**Comment by csnewman** [comment]
@AndreasTruetschel Thanks for the PR, I've merged it.

I will create a new NuGet release later today.

**Comment by CatoLeanTruetschel** [comment]
> I will create a new NuGet release later today.  

This would be awesome as I need this for my own project ;)

**Comment by csnewman** [comment]
I have published version 0.4.0 on NuGet. It is still indexing, however should be available soon.

```dotnet add package BlazorSignalR --version 0.4.0```

Let me know if you experience any issues via a new issue.
