### ISSUE TITLE
Out of process JSRuntime support

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [csnewman/BlazorSignalR#9]
As mentioned in https://github.com/csnewman/BlazorSignalR/issues/7 it would be beneficial if we could use a non-in-process js runtime. The current solution is to [wrap the js runtime](https://github.com/csnewman/BlazorSignalR/blob/master/src/BlazorSignalR/Internal/JSRuntimeWrapper.cs) and block. 

I have a working protoype [here](https://github.com/csnewman/BlazorSignalR/compare/master...AndreasTruetschel:master) where this is replaced with true async calls to the js runtime. This is working fine.

What I would like to test additionally is  Razor Components (server-side blazor) support. In contrast to the previous versions it is non-trivial to run both, server and client side blazor side-by-side within the same sample project. I didn't get it to work yet.  

@csnewman Should I add an additional *.Test.Server project that implements the Razor Components test? If server and client side blazor can run side-by-side in the future, these may be merged then.

**Comment by csnewman** [comment]
I would suggest opening a PR for the prototype so that it can be merged and published. And then an additional PR with the Server test project, where we can discuss the specifics there.
